### ISSUE TITLE
ipfs-websites-cluster is pulling wrong data

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-cluster/archive-tools#7]
Running the ipfs-cluster-follower for ipfs-websites resulted in unexpectedly high traffic.

I've searched to the log and the restarting pin operation for QmPHPxrruWCrqM9XjJWqw6cqd5zzphCww1oBjbf7BCv9L5 catched my eye.

I don't think this should be part of the websites - I guess it should be part of the Filecoin Params.

The full log:

[ipfs-websites.log](https://github.com/ipfs-cluster/archive-tools/files/4581721/ipfs-websites.log)

**Comment by hsanjuan** [comment]
QmPHPxrruWCrqM9XjJWqw6cqd5zzphCww1oBjbf7BCv9L5 is not part of the pinset for that cluster though?

**Comment by RubenKelevra** [comment]
Yeah, I know, but why is the ipfs-cluster-follower pulling it, was it accidentally part of the cluster in the history and the history gets wrongly merged?

In the chat a user was complaining about the same issue, and I checked at the time if there's any CID in the cluster with a large size - and there was none.

I have followed this cluster also quite often, and never had this issue before.

**Comment by hsanjuan** [comment]
I would have to check... technically if it was part of the archive and then deleted, then it should never even start pinning. It might be a bug in go-ds-crdt :/

**Comment by RubenKelevra** [comment]
> I would have to check... technically if it was part of the archive and then deleted, then it should never even start pinning.

Yeah I know. Maybe we have a race condition somewhere ... this time I'm writing to a Badger Datastore on a fast SSD - previously it was always a flat-fs one (for ipfs itself).

And this time I run the ipfs-cluster-follower as my used, while the IPFS daemon runs under as system user.

That's the only two differences I think to my previous installations.

> It might be a bug in go-ds-crdt :/

In this case definitely worth tracking down.

Here's the database etc if you want to look at it (password via Matrix):

https://ipfs.io/ipfs/bafybeiearofok46tvg56i5fsecvlu4dpe3urws5sxvl5mbapuv7apvbsay

**Comment by hsanjuan** [comment]
This is fixed in ipfs-cluster/master.

**Comment by Luflosi** [comment]
I'm having what looks like the same problem. I'm running `ipfs-cluster-follow ipfs-websites run --init ipfs-websites.collab.ipfscluster.io`. Over 100GB were downloaded so far (still not finished), which is a lot more than the 600MB advertised at https://collab.ipfscluster.io. I'm using ipfs-cluster-follow version 0.13.0 and IPFS version 0.7.0.
A couple months ago, I also tried following the cluster but had the same issue and then stopped following.
I'm happy to provide any additional information.

**Comment by hsanjuan** [comment]
I'll need to check, the problem above should have been fixed in 0.13.0.

**Comment by hsanjuan** [comment]
See https://github.com/ipfs-cluster/collab.ipfscluster.io/issues/19#issuecomment-759829039 (although 100GB seems a very high figure, are you sure that comes only from this archive?)

**Comment by Luflosi** [comment]
Yes, I'm quite sure that it only comes from this archive. I didn't download/serve via gateway/pin anything new besides following this cluster. After downloading about 350GB of data, I stopped the follower. That seems like a bit too much for just dist.ipfs.io. Maybe something else is being pinned?
Could you please try to reproduce the problem by starting a new follower, perhaps in a container or VM?
Alternatively, would the output from the cluster follower help diagnose the problem? I could remove the directory in ~/.ipfs-cluster-follow, start the follower again and record the output this time.

**Comment by hsanjuan** [comment]
It seems some Filecoin params are getting pinned on this cluster instead of the filecoin cluster. Working on removing that.

**Comment by hsanjuan** [comment]
So, the problem item should have been unpinned from this cluster. If you start the follower and GC it should free up space

**Comment by hsanjuan** [comment]
I have 22GB used in repo data, and I think I'm only pinning this archive.

**Comment by Luflosi** [comment]
After downloading a little over 2GB, everything is now pinned. I'm not sure how many files were already pinned so that they were not downloaded and didn't count towards this statistic.
Anyways, thank you for fixing this problem 🎉.
